apiVersion: v1
kind: ServiceAccount
metadata:
  name: logfwd
  namespace: collectors
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logfwd
  labels:
    app: logfwd
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logfwd
  labels:
    app: logfwd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logfwd
subjects:
  - kind: ServiceAccount
    name: logfwd
    namespace: collectors
