// @generated by scripts/generate_otlp_projection.py; DO NOT EDIT.
// spec: otlp_projection v1; opentelemetry-proto v1.8.0

use super::{ProjectionError, StringStorage, WireAny, WireField, WireScratch};
use ffwd_arrow::columnar::builder::ColumnarBatchBuilder;
use ffwd_arrow::columnar::plan::{BatchPlan, FieldHandle, FieldKind};
use ffwd_types::field_names;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum WireKind {
    Varint,
    Fixed64,
    Len,
    StartGroup,
    EndGroup,
    Fixed32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum ProjectionAction {
    Project,
    Descend,
    Ignore,
    Unsupported,
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum MessageKind {
    ExportLogsServiceRequest,
    ResourceLogs,
    Resource,
    ScopeLogs,
    InstrumentationScope,
    LogRecord,
    KeyValue,
    AnyValue,
    ArrayValue,
    KeyValueList,
}

#[derive(Clone, Copy, Debug)]
pub(super) struct FieldRule {
    #[allow(dead_code)]
    pub(super) number: u32,
    #[allow(dead_code)]
    pub(super) name: &'static str,
    pub(super) expected_wire: WireKind,
    pub(super) action: ProjectionAction,
    pub(super) child: Option<MessageKind>,
}

#[allow(dead_code)]
pub(super) mod field_numbers {
    pub(crate) const EXPORT_LOGS_REQUEST_RESOURCE_LOGS: u32 = 1;
    pub(crate) const RESOURCE_LOGS_RESOURCE: u32 = 1;
    pub(crate) const RESOURCE_LOGS_SCOPE_LOGS: u32 = 2;
    pub(crate) const RESOURCE_LOGS_SCHEMA_URL: u32 = 3;
    pub(crate) const RESOURCE_ATTRIBUTES: u32 = 1;
    pub(crate) const RESOURCE_DROPPED_ATTRIBUTES_COUNT: u32 = 2;
    pub(crate) const RESOURCE_ENTITY_REFS: u32 = 3;
    pub(crate) const SCOPE_LOGS_SCOPE: u32 = 1;
    pub(crate) const SCOPE_LOGS_LOG_RECORDS: u32 = 2;
    pub(crate) const SCOPE_LOGS_SCHEMA_URL: u32 = 3;
    pub(crate) const INSTRUMENTATION_SCOPE_NAME: u32 = 1;
    pub(crate) const INSTRUMENTATION_SCOPE_VERSION: u32 = 2;
    pub(crate) const INSTRUMENTATION_SCOPE_ATTRIBUTES: u32 = 3;
    pub(crate) const INSTRUMENTATION_SCOPE_DROPPED_ATTRIBUTES_COUNT: u32 = 4;
    pub(crate) const LOG_RECORD_TIME_UNIX_NANO: u32 = 1;
    pub(crate) const LOG_RECORD_SEVERITY_NUMBER: u32 = 2;
    pub(crate) const LOG_RECORD_SEVERITY_TEXT: u32 = 3;
    pub(crate) const LOG_RECORD_BODY: u32 = 5;
    pub(crate) const LOG_RECORD_ATTRIBUTES: u32 = 6;
    pub(crate) const LOG_RECORD_DROPPED_ATTRIBUTES_COUNT: u32 = 7;
    pub(crate) const LOG_RECORD_FLAGS: u32 = 8;
    pub(crate) const LOG_RECORD_TRACE_ID: u32 = 9;
    pub(crate) const LOG_RECORD_SPAN_ID: u32 = 10;
    pub(crate) const LOG_RECORD_OBSERVED_TIME_UNIX_NANO: u32 = 11;
    pub(crate) const LOG_RECORD_EVENT_NAME: u32 = 12;
    pub(crate) const KEY_VALUE_KEY: u32 = 1;
    pub(crate) const KEY_VALUE_VALUE: u32 = 2;
    pub(crate) const ANY_VALUE_STRING_VALUE: u32 = 1;
    pub(crate) const ANY_VALUE_BOOL_VALUE: u32 = 2;
    pub(crate) const ANY_VALUE_INT_VALUE: u32 = 3;
    pub(crate) const ANY_VALUE_DOUBLE_VALUE: u32 = 4;
    pub(crate) const ANY_VALUE_ARRAY_VALUE: u32 = 5;
    pub(crate) const ANY_VALUE_KVLIST_VALUE: u32 = 6;
    pub(crate) const ANY_VALUE_BYTES_VALUE: u32 = 7;
}

pub(super) const EXPORTLOGSSERVICEREQUEST_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "resource_logs",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::ResourceLogs),
}];

pub(super) const RESOURCELOGS_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "resource",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::Resource),
    },
    FieldRule {
        number: 2,
        name: "scope_logs",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::ScopeLogs),
    },
    FieldRule {
        number: 3,
        name: "schema_url",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const RESOURCE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::KeyValue),
    },
    FieldRule {
        number: 2,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "entity_refs",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const SCOPELOGS_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "scope",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::InstrumentationScope),
    },
    FieldRule {
        number: 2,
        name: "log_records",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::LogRecord),
    },
    FieldRule {
        number: 3,
        name: "schema_url",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const INSTRUMENTATIONSCOPE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "name",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "version",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 4,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const LOGRECORD_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "time_unix_nano",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "severity_number",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "severity_text",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 5,
        name: "body",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::AnyValue),
    },
    FieldRule {
        number: 6,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::KeyValue),
    },
    FieldRule {
        number: 7,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 8,
        name: "flags",
        expected_wire: WireKind::Fixed32,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 9,
        name: "trace_id",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 10,
        name: "span_id",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 11,
        name: "observed_time_unix_nano",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 12,
        name: "event_name",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const KEYVALUE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "key",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::AnyValue),
    },
];

pub(super) const ANYVALUE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "string_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "bool_value",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "int_value",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 4,
        name: "double_value",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 5,
        name: "array_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 6,
        name: "kvlist_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 7,
        name: "bytes_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
];

pub(super) const ARRAYVALUE_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "values",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::AnyValue),
}];

pub(super) const KEYVALUELIST_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "values",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::KeyValue),
}];

#[allow(dead_code)]
pub(super) fn fields_for(message: MessageKind) -> &'static [FieldRule] {
    match message {
        MessageKind::ExportLogsServiceRequest => EXPORTLOGSSERVICEREQUEST_FIELDS,
        MessageKind::ResourceLogs => RESOURCELOGS_FIELDS,
        MessageKind::Resource => RESOURCE_FIELDS,
        MessageKind::ScopeLogs => SCOPELOGS_FIELDS,
        MessageKind::InstrumentationScope => INSTRUMENTATIONSCOPE_FIELDS,
        MessageKind::LogRecord => LOGRECORD_FIELDS,
        MessageKind::KeyValue => KEYVALUE_FIELDS,
        MessageKind::AnyValue => ANYVALUE_FIELDS,
        MessageKind::ArrayValue => ARRAYVALUE_FIELDS,
        MessageKind::KeyValueList => KEYVALUELIST_FIELDS,
    }
}
