pipelines:
  default:
    inputs:
      - type: generator
    outputs:
      - type: elasticsearch
        endpoint: http://127.0.0.1:9200
        index: ffwd-bench
server:
  diagnostics: 127.0.0.1:9090
