#!/usr/bin/env python3
"""Generate the v1 OTLP fast-row encoder from vendored OTLP protos.

This generator is intentionally narrow. It emits only the row-level OTLP
projection code and relies on handwritten/shared envelope + wire helpers. The
OTLP field metadata is read from the checked-in OpenTelemetry proto files; the
only repo-local policy here is how Arrow input columns map onto LogRecord roles.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

from otlp_proto import parse_proto_fields, vendored_proto_root


REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "crates" / "logfwd-output" / "src" / "generated" / "otlp_log_record_fast_v1.rs"
PROTO_BASE = REPO / "crates" / "logfwd-io" / "codegen" / "opentelemetry-proto"
PROTO_ROOT = vendored_proto_root(PROTO_BASE)
PROTO_VERSION = PROTO_ROOT.name
PROTO_FILES = [
    PROTO_ROOT / "opentelemetry" / "proto" / "logs" / "v1" / "logs.proto",
    PROTO_ROOT / "opentelemetry" / "proto" / "resource" / "v1" / "resource.proto",
    PROTO_ROOT / "opentelemetry" / "proto" / "common" / "v1" / "common.proto",
]

ROLE_ALIASES = [
    {"name": "timestamp", "fields": ["time_unix_nano"], "sources": ["timestamp", "time"]},
    {
        "name": "severity",
        "fields": ["severity_number", "severity_text"],
        "sources": ["level", "severity_text"],
    },
    {"name": "body", "fields": ["body"], "sources": ["body", "message"]},
    {"name": "trace_id", "fields": ["trace_id"], "sources": ["trace_id"]},
    {"name": "span_id", "fields": ["span_id"], "sources": ["span_id"]},
    {"name": "flags", "fields": ["flags"], "sources": ["flags", "trace_flags"]},
    {"name": "attributes", "fields": ["attributes"], "sources": ["*"]},
]

LOG_RECORD_FIELD_EXPECTATIONS = {
    "time_unix_nano": {"proto_type": "fixed64", "wire": "fixed64", "repeated": False},
    "observed_time_unix_nano": {"proto_type": "fixed64", "wire": "fixed64", "repeated": False},
    "severity_number": {"proto_type": "SeverityNumber", "wire": "varint", "repeated": False},
    "severity_text": {"proto_type": "string", "wire": "len", "repeated": False},
    "body": {"proto_type": "AnyValue", "wire": "len", "repeated": False},
    "attributes": {"proto_type": "KeyValue", "wire": "len", "repeated": True},
    "flags": {"proto_type": "fixed32", "wire": "fixed32", "repeated": False},
    "trace_id": {"proto_type": "bytes", "wire": "len", "repeated": False},
    "span_id": {"proto_type": "bytes", "wire": "len", "repeated": False},
}

def load_spec() -> dict:
    messages = parse_proto_fields(PROTO_FILES)
    log_record_fields = messages.get("LogRecord")
    any_value_fields = messages.get("AnyValue")
    if log_record_fields is None:
        raise ValueError("LogRecord missing from vendored OTLP proto files")
    if any_value_fields is None:
        raise ValueError("AnyValue missing from vendored OTLP proto files")

    for field_name, expectations in LOG_RECORD_FIELD_EXPECTATIONS.items():
        field = log_record_fields.get(field_name)
        if field is None:
            raise ValueError(f"LogRecord.{field_name} missing from vendored OTLP proto files")
        for key, expected in expectations.items():
            actual = field[key]
            if actual != expected:
                raise ValueError(
                    f"LogRecord.{field_name} {key} changed: "
                    f"expected={expected} proto={actual}"
                )

    for role in ROLE_ALIASES:
        for field_name in role["fields"]:
            if field_name not in log_record_fields:
                raise ValueError(f"LogRecord.{field_name} missing from vendored OTLP proto files")

    supported_any_values = {
        "string_value": "string",
        "bool_value": "bool",
        "int_value": "int64",
        "double_value": "double",
        "bytes_value": "bytes",
    }
    for field_name, proto_type in supported_any_values.items():
        field = any_value_fields.get(field_name)
        if field is None:
            raise ValueError(f"AnyValue.{field_name} missing from vendored OTLP proto files")
        if field["proto_type"] != proto_type:
            raise ValueError(
                f"AnyValue.{field_name} type changed: expected={proto_type} "
                f"proto={field['proto_type']}"
            )

    return {
        "name": "otlp_log_record_fast",
        "version": 1,
        "proto_version": PROTO_VERSION,
        "roles": ROLE_ALIASES,
        "log_record_fields": log_record_fields,
    }


def render(spec: dict) -> str:
    roles = spec["roles"]
    role_order = ", ".join(f'"{role["name"]}"' for role in roles)
    proto_fields = ", ".join(
        f'{field["name"]}={field["number"]}:{field["wire"]}'
        for field in sorted(spec["log_record_fields"].values(), key=lambda field: field["number"])
    )
    return f"""// @generated by scripts/generate_otlp_fast_encoder.py; DO NOT EDIT.
// spec: {spec["name"]} v{spec["version"]}; opentelemetry-proto {spec["proto_version"]}
// role order: {role_order}
// LogRecord proto fields: {proto_fields}

use arrow::array::Array;
use super::{{BatchColumns, BatchMetadata, encode_col_attr, encode_fixed32, encode_tag,
    encode_varint, numeric_timestamp_ns}};
use logfwd_core::otlp::{{self, Severity, bytes_field_size, encode_bytes_field, encode_fixed64,
    encode_varint_field, hex_decode, parse_severity, parse_timestamp_nanos}};

/// Generated v1 OTLP LogRecord encoder.
pub(super) fn encode_row_as_log_record_fast_v1(
    columns: &BatchColumns<'_>,
    row: usize,
    metadata: &BatchMetadata,
    buf: &mut Vec<u8>,
) {{
    let timestamp_ns: Option<u64> = if let Some((_, arr)) = columns.timestamp_num_col.as_ref() {{
        numeric_timestamp_ns(*arr, row)
    }} else if let Some((_, arr)) = columns.timestamp_col.as_ref() {{
        if arr.is_null(row) {{
            None
        }} else {{
            match parse_timestamp_nanos(arr.value(row).as_bytes()) {{
                Some(ts) => Some(ts),
                None => {{
                    tracing::debug!("timestamp parse fallback: event_time omitted for unparsable value");
                    None
                }}
            }}
        }}
    }} else {{
        None
    }};

    let (severity_num, severity_text): (Severity, &[u8]) =
        if let Some((_, arr)) = columns.level_col.as_ref() {{
            if arr.is_null(row) {{
                (Severity::Unspecified, b"")
            }} else {{
                parse_severity(arr.value(row).as_bytes())
            }}
        }} else {{
            (Severity::Unspecified, b"")
        }};
    let severity_number = if let Some((_, arr)) = columns.severity_num_col.as_ref() {{
        if arr.is_null(row) {{
            severity_num as u64
        }} else {{
            u64::try_from(arr.value(row)).unwrap_or(0)
        }}
    }} else {{
        severity_num as u64
    }};

    let body: &str = match columns.body_col.as_ref() {{
        Some((_, body)) if !body.is_null(row) => body.value(row),
        _ => "",
    }};
    let body_bytes = body.as_bytes();

    if let Some(timestamp_ns) = timestamp_ns {{
        encode_fixed64(buf, otlp::LOG_RECORD_TIME_UNIX_NANO, timestamp_ns);
    }}

    if severity_number > 0 {{
        encode_varint_field(buf, otlp::LOG_RECORD_SEVERITY_NUMBER, severity_number);
    }}

    if !severity_text.is_empty() {{
        encode_bytes_field(buf, otlp::LOG_RECORD_SEVERITY_TEXT, severity_text);
    }}

    if !body_bytes.is_empty() {{
        let anyvalue_inner_size = bytes_field_size(otlp::ANY_VALUE_STRING_VALUE, body_bytes.len());
        encode_tag(buf, otlp::LOG_RECORD_BODY, otlp::WIRE_TYPE_LEN);
        encode_varint(buf, anyvalue_inner_size as u64);
        encode_bytes_field(buf, otlp::ANY_VALUE_STRING_VALUE, body_bytes);
    }}

    for col in &columns.attribute_cols {{
        encode_col_attr(buf, otlp::LOG_RECORD_ATTRIBUTES, col, row);
    }}

    if let Some((_, arr)) = columns.flags_col
        && let Some(flags) = arr.value_u32(row) {{
            encode_fixed32(buf, otlp::LOG_RECORD_FLAGS, flags);
        }}

    if let Some((_, arr)) = columns.trace_id_col.as_ref()
        && !arr.is_null(row) {{
            let hex = arr.value(row);
            let mut decoded = [0u8; 16];
            if hex_decode(hex.as_bytes(), &mut decoded) {{
                encode_bytes_field(buf, otlp::LOG_RECORD_TRACE_ID, &decoded);
            }}
        }}

    if let Some((_, arr)) = columns.span_id_col.as_ref()
        && !arr.is_null(row) {{
            let hex = arr.value(row);
            let mut decoded = [0u8; 8];
            if hex_decode(hex.as_bytes(), &mut decoded) {{
                encode_bytes_field(buf, otlp::LOG_RECORD_SPAN_ID, &decoded);
            }}
        }}

    let observed_ns = columns
        .observed_ts_col
        .as_ref()
        .and_then(|(_, arr)| numeric_timestamp_ns(*arr, row))
        .unwrap_or(metadata.observed_time_ns);
    encode_fixed64(buf, otlp::LOG_RECORD_OBSERVED_TIME_UNIX_NANO, observed_ns);
}}
"""


def check_output(rendered: str) -> int:
    current = OUT.read_text() if OUT.exists() else ""
    if current == rendered:
        return 0

    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        rendered.splitlines(keepends=True),
        fromfile=str(OUT),
        tofile=f"{OUT} (generated)",
    )
    sys.stderr.writelines(diff)
    sys.stderr.write(
        "\nGenerated OTLP fast encoder is out of date. "
        "Run `python3 scripts/generate_otlp_fast_encoder.py`.\n"
    )
    return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in generated file matches the generator output",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render(load_spec())
    if args.check:
        return check_output(rendered)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
