use ffwd_config::{Config, docspec};
use wasm_bindgen::prelude::*;

// ── Template data ──────────────────────────────────────────────────────────
// All template data lives in `ffwd-config::docspec`.  This module re-exports
// from there to eliminate the risk of drift between the CLI wizard, the
// browser-based config builder, and the generated docs.
//
// Use-case templates use `UseCaseDoc` from docspec (serialized as camelCase
// JSON for the JS side).
pub(crate) type UseCaseTemplate = docspec::UseCaseDoc;
const USE_CASE_TEMPLATES: &[UseCaseTemplate] = docspec::USE_CASE_TEMPLATES;

// ── WASM exports ───────────────────────────────────────────────────────────

/// Returns the list of available input templates as a JSON array.
#[wasm_bindgen]
pub fn get_input_templates() -> JsValue {
    serde_wasm_bindgen_or_json(docspec::INPUT_TEMPLATES)
}

/// Returns the list of available output templates as a JSON array.
#[wasm_bindgen]
pub fn get_output_templates() -> JsValue {
    serde_wasm_bindgen_or_json(docspec::OUTPUT_TEMPLATES)
}

/// Returns the list of use-case starter presets as a JSON array.
#[wasm_bindgen]
pub fn get_use_case_templates() -> JsValue {
    serde_wasm_bindgen_or_json(USE_CASE_TEMPLATES)
}

/// Assemble a config YAML from template IDs and an optional SQL transform.
///
/// Returns the YAML string, or throws a JS error if the IDs are not found.
#[wasm_bindgen]
pub fn render_config(
    input_id: &str,
    output_id: &str,
    transform_sql: &str,
) -> Result<String, JsValue> {
    let input = docspec::input_template(input_id)
        .ok_or_else(|| JsValue::from_str(&format!("unknown input template: {input_id}")))?;

    let output = docspec::output_template(output_id)
        .ok_or_else(|| JsValue::from_str(&format!("unknown output template: {output_id}")))?;

    let mut out = String::from("# Generated by ffwd config builder\n");
    out.push_str("# Fill in paths, endpoints, and credentials for your environment.\n\n");
    out.push_str("pipelines:\n  default:\n");
    push_pipeline_item_body(&mut out, "inputs", input.snippet);
    if !transform_sql.trim().is_empty() {
        out.push_str("    transform: |\n");
        for line in transform_sql.lines() {
            out.push_str("      ");
            out.push_str(line);
            out.push('\n');
        }
    }
    push_pipeline_item_body(&mut out, "outputs", output.snippet);
    out.push_str("\n# Optional: diagnostics server\n# server:\n#   diagnostics: 127.0.0.1:9191\n");
    Ok(out)
}

/// Validate a ffwd config YAML string.
///
/// Returns `undefined` on success, or throws a JS error with the validation
/// message on failure.
#[wasm_bindgen]
pub fn validate_config(yaml: &str) -> Result<(), JsValue> {
    Config::load_str(yaml)
        .map(|_| ())
        .map_err(|e| JsValue::from_str(&e.to_string()))
}

/// Returns the snippet for a single input template by ID.
#[wasm_bindgen]
pub fn get_input_snippet(id: &str) -> Option<String> {
    docspec::input_template(id).map(|template| template.snippet.to_string())
}

/// Returns the snippet for a single output template by ID.
#[wasm_bindgen]
pub fn get_output_snippet(id: &str) -> Option<String> {
    docspec::output_template(id).map(|template| template.snippet.to_string())
}

// ── Helpers ────────────────────────────────────────────────────────────────

fn serde_wasm_bindgen_or_json<T: serde::Serialize + ?Sized>(value: &T) -> JsValue {
    // Serialize to JSON string then parse — avoids needing serde-wasm-bindgen.
    // All callers pass compile-time static data; serialization cannot fail.
    let json = serde_json::to_string(value).expect("static template data serialization failed");
    js_sys::JSON::parse(&json).expect("static template data produced invalid JSON")
}

fn push_pipeline_item_body(out: &mut String, section_name: &str, snippet_body: &str) {
    let mut lines = snippet_body.lines().filter(|line| !line.trim().is_empty());
    if let Some(first) = lines.next() {
        out.push_str("    ");
        out.push_str(section_name);
        out.push_str(":\n");
        out.push_str("      - ");
        out.push_str(first.trim_start());
        out.push('\n');
        for line in lines {
            out.push_str("        ");
            out.push_str(line);
            out.push('\n');
        }
    }
}
