// @generated by scripts/generate_otlp_projection.py; DO NOT EDIT.
// spec: otlp_projection v1; opentelemetry-proto v1.8.0

use super::{ProjectionError, StringStorage, WireAny, WireField, WireScratch};
use ffwd_arrow::columnar::builder::ColumnarBatchBuilder;
use ffwd_arrow::columnar::plan::{BatchPlan, FieldHandle, FieldKind};
use ffwd_types::field_names;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum WireKind {
    Varint,
    Fixed64,
    Len,
    StartGroup,
    EndGroup,
    Fixed32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum ProjectionAction {
    Project,
    Descend,
    Ignore,
    Unsupported,
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum MessageKind {
    ExportLogsServiceRequest,
    ResourceLogs,
    Resource,
    ScopeLogs,
    InstrumentationScope,
    LogRecord,
    KeyValue,
    AnyValue,
    ArrayValue,
    KeyValueList,
}

#[derive(Clone, Copy, Debug)]
pub(super) struct FieldRule {
    #[allow(dead_code)]
    pub(super) number: u32,
    #[allow(dead_code)]
    pub(super) name: &'static str,
    pub(super) expected_wire: WireKind,
    pub(super) action: ProjectionAction,
    pub(super) child: Option<MessageKind>,
}

#[allow(dead_code)]
pub(super) mod field_numbers {
    pub(crate) const EXPORT_LOGS_REQUEST_RESOURCE_LOGS: u32 = 1;
    pub(crate) const RESOURCE_LOGS_RESOURCE: u32 = 1;
    pub(crate) const RESOURCE_LOGS_SCOPE_LOGS: u32 = 2;
    pub(crate) const RESOURCE_LOGS_SCHEMA_URL: u32 = 3;
    pub(crate) const RESOURCE_ATTRIBUTES: u32 = 1;
    pub(crate) const RESOURCE_DROPPED_ATTRIBUTES_COUNT: u32 = 2;
    pub(crate) const RESOURCE_ENTITY_REFS: u32 = 3;
    pub(crate) const SCOPE_LOGS_SCOPE: u32 = 1;
    pub(crate) const SCOPE_LOGS_LOG_RECORDS: u32 = 2;
    pub(crate) const SCOPE_LOGS_SCHEMA_URL: u32 = 3;
    pub(crate) const INSTRUMENTATION_SCOPE_NAME: u32 = 1;
    pub(crate) const INSTRUMENTATION_SCOPE_VERSION: u32 = 2;
    pub(crate) const INSTRUMENTATION_SCOPE_ATTRIBUTES: u32 = 3;
    pub(crate) const INSTRUMENTATION_SCOPE_DROPPED_ATTRIBUTES_COUNT: u32 = 4;
    pub(crate) const LOG_RECORD_TIME_UNIX_NANO: u32 = 1;
    pub(crate) const LOG_RECORD_SEVERITY_NUMBER: u32 = 2;
    pub(crate) const LOG_RECORD_SEVERITY_TEXT: u32 = 3;
    pub(crate) const LOG_RECORD_BODY: u32 = 5;
    pub(crate) const LOG_RECORD_ATTRIBUTES: u32 = 6;
    pub(crate) const LOG_RECORD_DROPPED_ATTRIBUTES_COUNT: u32 = 7;
    pub(crate) const LOG_RECORD_FLAGS: u32 = 8;
    pub(crate) const LOG_RECORD_TRACE_ID: u32 = 9;
    pub(crate) const LOG_RECORD_SPAN_ID: u32 = 10;
    pub(crate) const LOG_RECORD_OBSERVED_TIME_UNIX_NANO: u32 = 11;
    pub(crate) const LOG_RECORD_EVENT_NAME: u32 = 12;
    pub(crate) const KEY_VALUE_KEY: u32 = 1;
    pub(crate) const KEY_VALUE_VALUE: u32 = 2;
    pub(crate) const ANY_VALUE_STRING_VALUE: u32 = 1;
    pub(crate) const ANY_VALUE_BOOL_VALUE: u32 = 2;
    pub(crate) const ANY_VALUE_INT_VALUE: u32 = 3;
    pub(crate) const ANY_VALUE_DOUBLE_VALUE: u32 = 4;
    pub(crate) const ANY_VALUE_ARRAY_VALUE: u32 = 5;
    pub(crate) const ANY_VALUE_KVLIST_VALUE: u32 = 6;
    pub(crate) const ANY_VALUE_BYTES_VALUE: u32 = 7;
}

pub(super) const EXPORTLOGSSERVICEREQUEST_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "resource_logs",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::ResourceLogs),
}];

pub(super) const RESOURCELOGS_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "resource",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::Resource),
    },
    FieldRule {
        number: 2,
        name: "scope_logs",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::ScopeLogs),
    },
    FieldRule {
        number: 3,
        name: "schema_url",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const RESOURCE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::KeyValue),
    },
    FieldRule {
        number: 2,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "entity_refs",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const SCOPELOGS_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "scope",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::InstrumentationScope),
    },
    FieldRule {
        number: 2,
        name: "log_records",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::LogRecord),
    },
    FieldRule {
        number: 3,
        name: "schema_url",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const INSTRUMENTATIONSCOPE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "name",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "version",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 4,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const LOGRECORD_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "time_unix_nano",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "severity_number",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "severity_text",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 5,
        name: "body",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::AnyValue),
    },
    FieldRule {
        number: 6,
        name: "attributes",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::KeyValue),
    },
    FieldRule {
        number: 7,
        name: "dropped_attributes_count",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Ignore,
        child: None,
    },
    FieldRule {
        number: 8,
        name: "flags",
        expected_wire: WireKind::Fixed32,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 9,
        name: "trace_id",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 10,
        name: "span_id",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 11,
        name: "observed_time_unix_nano",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 12,
        name: "event_name",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Ignore,
        child: None,
    },
];

pub(super) const KEYVALUE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "key",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Descend,
        child: Some(MessageKind::AnyValue),
    },
];

pub(super) const ANYVALUE_FIELDS: &[FieldRule] = &[
    FieldRule {
        number: 1,
        name: "string_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 2,
        name: "bool_value",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 3,
        name: "int_value",
        expected_wire: WireKind::Varint,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 4,
        name: "double_value",
        expected_wire: WireKind::Fixed64,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 5,
        name: "array_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 6,
        name: "kvlist_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
    FieldRule {
        number: 7,
        name: "bytes_value",
        expected_wire: WireKind::Len,
        action: ProjectionAction::Project,
        child: None,
    },
];

pub(super) const ARRAYVALUE_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "values",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::AnyValue),
}];

pub(super) const KEYVALUELIST_FIELDS: &[FieldRule] = &[FieldRule {
    number: 1,
    name: "values",
    expected_wire: WireKind::Len,
    action: ProjectionAction::Descend,
    child: Some(MessageKind::KeyValue),
}];

#[allow(dead_code)]
pub(super) fn fields_for(message: MessageKind) -> &'static [FieldRule] {
    match message {
        MessageKind::ExportLogsServiceRequest => EXPORTLOGSSERVICEREQUEST_FIELDS,
        MessageKind::ResourceLogs => RESOURCELOGS_FIELDS,
        MessageKind::Resource => RESOURCE_FIELDS,
        MessageKind::ScopeLogs => SCOPELOGS_FIELDS,
        MessageKind::InstrumentationScope => INSTRUMENTATIONSCOPE_FIELDS,
        MessageKind::LogRecord => LOGRECORD_FIELDS,
        MessageKind::KeyValue => KEYVALUE_FIELDS,
        MessageKind::AnyValue => ANYVALUE_FIELDS,
        MessageKind::ArrayValue => ARRAYVALUE_FIELDS,
        MessageKind::KeyValueList => KEYVALUELIST_FIELDS,
    }
}

pub(super) fn classify_projection_support(input: &[u8]) -> Result<(), ProjectionError> {
    scan_message(input, MessageKind::ExportLogsServiceRequest)
}

pub(super) struct OtlpFieldHandles {
    pub(super) timestamp: FieldHandle,
    pub(super) observed_timestamp: FieldHandle,
    pub(super) severity: FieldHandle,
    pub(super) severity_number: FieldHandle,
    pub(super) body: FieldHandle,
    pub(super) trace_id: FieldHandle,
    pub(super) span_id: FieldHandle,
    pub(super) flags: FieldHandle,
    pub(super) scope_name: FieldHandle,
    pub(super) scope_version: FieldHandle,
}

impl OtlpFieldHandles {
    pub(super) fn write_timestamp(&self, builder: &mut ColumnarBatchBuilder, value: i64) {
        builder.write_i64(self.timestamp, value);
    }

    pub(super) fn write_observed_timestamp(&self, builder: &mut ColumnarBatchBuilder, value: i64) {
        builder.write_i64(self.observed_timestamp, value);
    }

    pub(super) fn write_severity(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: &[u8],
        string_storage: StringStorage,
    ) -> Result<(), ProjectionError> {
        super::write_wire_str(builder, self.severity, value, string_storage)
    }

    pub(super) fn write_severity_number(&self, builder: &mut ColumnarBatchBuilder, value: i64) {
        builder.write_i64(self.severity_number, value);
    }

    pub(super) fn write_body(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: WireAny<'_>,
        scratch: &mut WireScratch,
        string_storage: StringStorage,
    ) -> Result<(), ProjectionError> {
        write_wire_any_as_string(builder, self.body, value, scratch, string_storage)
    }

    pub(super) fn write_trace_id(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: &[u8],
    ) -> Result<(), ProjectionError> {
        super::write_hex_field(builder, self.trace_id, value)
    }

    pub(super) fn write_span_id(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: &[u8],
    ) -> Result<(), ProjectionError> {
        super::write_hex_field(builder, self.span_id, value)
    }

    pub(super) fn write_flags(&self, builder: &mut ColumnarBatchBuilder, value: i64) {
        builder.write_i64(self.flags, value);
    }

    pub(super) fn write_scope_name(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: &[u8],
        string_storage: StringStorage,
    ) -> Result<(), ProjectionError> {
        super::write_wire_str(builder, self.scope_name, value, string_storage)
    }

    pub(super) fn write_scope_version(
        &self,
        builder: &mut ColumnarBatchBuilder,
        value: &[u8],
        string_storage: StringStorage,
    ) -> Result<(), ProjectionError> {
        super::write_wire_str(builder, self.scope_version, value, string_storage)
    }
}

pub(super) fn build_otlp_plan() -> (BatchPlan, OtlpFieldHandles) {
    let mut plan = BatchPlan::new();
    let handles = OtlpFieldHandles {
        timestamp: plan
            .declare_planned(field_names::TIMESTAMP, FieldKind::Int64)
            .expect("duplicate planned field"),
        observed_timestamp: plan
            .declare_planned(field_names::OBSERVED_TIMESTAMP, FieldKind::Int64)
            .expect("duplicate planned field"),
        severity: plan
            .declare_planned(field_names::SEVERITY, FieldKind::Utf8View)
            .expect("duplicate planned field"),
        severity_number: plan
            .declare_planned(field_names::SEVERITY_NUMBER, FieldKind::Int64)
            .expect("duplicate planned field"),
        body: plan
            .declare_planned(field_names::BODY, FieldKind::Utf8View)
            .expect("duplicate planned field"),
        trace_id: plan
            .declare_planned(field_names::TRACE_ID, FieldKind::Utf8View)
            .expect("duplicate planned field"),
        span_id: plan
            .declare_planned(field_names::SPAN_ID, FieldKind::Utf8View)
            .expect("duplicate planned field"),
        flags: plan
            .declare_planned(field_names::FLAGS, FieldKind::Int64)
            .expect("duplicate planned field"),
        scope_name: plan
            .declare_planned(field_names::SCOPE_NAME, FieldKind::Utf8View)
            .expect("duplicate planned field"),
        scope_version: plan
            .declare_planned(field_names::SCOPE_VERSION, FieldKind::Utf8View)
            .expect("duplicate planned field"),
    };
    (plan, handles)
}

#[derive(Clone, Copy, Default)]
pub(super) struct ScopeFields<'a> {
    pub(super) name: Option<&'a [u8]>,
    pub(super) version: Option<&'a [u8]>,
}

pub(super) fn merge_scope_wire<'a>(
    scope: &'a [u8],
    scope_fields: &mut ScopeFields<'a>,
) -> Result<(), ProjectionError> {
    super::for_each_field(scope, |field, value| {
        match (field, value) {
            (1, WireField::Len(value)) => {
                scope_fields.name = Some(super::require_utf8(value, "invalid UTF-8 scope name")?);
            }
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for InstrumentationScope.name",
                ));
            }
            (2, WireField::Len(value)) => {
                scope_fields.version =
                    Some(super::require_utf8(value, "invalid UTF-8 scope version")?);
            }
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for InstrumentationScope.version",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

#[derive(Clone, Copy, Default)]
pub(super) struct LogRecordFields<'a> {
    pub(super) time_unix_nano: u64,
    pub(super) observed_time_unix_nano: u64,
    pub(super) severity_number: i64,
    pub(super) severity_text: Option<&'a [u8]>,
    pub(super) body: Option<WireAny<'a>>,
    pub(super) trace_id: Option<&'a [u8]>,
    pub(super) span_id: Option<&'a [u8]>,
    pub(super) flags: i64,
}

pub(super) fn decode_log_record_fields<'a>(
    log_record: &'a [u8],
    attr_ranges: &mut Vec<(usize, usize)>,
) -> Result<LogRecordFields<'a>, ProjectionError> {
    let mut out = LogRecordFields::default();
    super::for_each_field(log_record, |field, value| {
        match (field, value) {
            (1, WireField::Fixed64(value)) => {
                out.time_unix_nano = value;
            }
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.time_unix_nano",
                ));
            }
            (11, WireField::Fixed64(value)) => {
                out.observed_time_unix_nano = value;
            }
            (11, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.observed_time_unix_nano",
                ));
            }
            (2, WireField::Varint(value)) => {
                out.severity_number = i64::from(value as i32);
            }
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.severity_number",
                ));
            }
            (3, WireField::Len(value)) => {
                out.severity_text = if value.is_empty() {
                    None
                } else {
                    Some(super::require_utf8(value, "invalid UTF-8 severity text")?)
                };
            }
            (3, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.severity_text",
                ));
            }
            (5, WireField::Len(value)) => {
                if let Some(value) = decode_any_value_wire(value)? {
                    out.body = Some(value);
                }
            }
            (5, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.body",
                ));
            }
            (9, WireField::Len(value)) => {
                out.trace_id = (!value.is_empty()).then_some(value);
            }
            (9, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.trace_id",
                ));
            }
            (10, WireField::Len(value)) => {
                out.span_id = (!value.is_empty()).then_some(value);
            }
            (10, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.span_id",
                ));
            }
            (8, WireField::Fixed32(value)) => {
                out.flags = i64::from(value);
            }
            (8, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.flags",
                ));
            }
            (6, WireField::Len(value)) => {
                attr_ranges.push(super::subslice_range(log_record, value)?);
            }
            (6, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for LogRecord.attributes",
                ));
            }
            _ => {}
        }
        Ok(())
    })?;
    Ok(out)
}

pub(super) fn for_each_export_resource_logs<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (1, WireField::Len(bytes)) => visit(bytes)?,
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for ExportLogsServiceRequest.resource_logs",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn for_each_resource_logs_resource<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (1, WireField::Len(bytes)) => visit(bytes)?,
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for ResourceLogs.resource",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn for_each_resource_logs_scope_logs<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (2, WireField::Len(bytes)) => visit(bytes)?,
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for ResourceLogs.scope_logs",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn for_each_resource_attribute<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (1, WireField::Len(bytes)) => visit(bytes)?,
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for Resource.attributes",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn for_each_scope_logs_scope<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (1, WireField::Len(bytes)) => visit(bytes)?,
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for ScopeLogs.scope",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn for_each_scope_logs_log_record<'a>(
    input: &'a [u8],
    mut visit: impl FnMut(&'a [u8]) -> Result<(), ProjectionError>,
) -> Result<(), ProjectionError> {
    super::for_each_field(input, |field, value| {
        match (field, value) {
            (2, WireField::Len(bytes)) => visit(bytes)?,
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for ScopeLogs.log_records",
                ));
            }
            _ => {}
        }
        Ok(())
    })
}

pub(super) fn decode_any_value_wire(value: &[u8]) -> Result<Option<WireAny<'_>>, ProjectionError> {
    let mut out = None;
    super::for_each_field(value, |field, field_value| {
        match (field, field_value) {
            (1, WireField::Len(bytes)) => {
                out = Some(WireAny::String(super::require_utf8(
                    bytes,
                    "invalid UTF-8 AnyValue string",
                )?));
            }
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.string_value",
                ));
            }
            (2, WireField::Varint(value)) => {
                out = Some(WireAny::Bool(value != 0));
            }
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.bool_value",
                ));
            }
            (3, WireField::Varint(value)) => {
                out = Some(WireAny::Int(value as i64));
            }
            (3, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.int_value",
                ));
            }
            (4, WireField::Fixed64(value)) => {
                out = Some(WireAny::Double(f64::from_bits(value)));
            }
            (4, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.double_value",
                ));
            }
            (5, WireField::Len(bytes)) => {
                out = Some(WireAny::ArrayRaw(bytes));
            }
            (5, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.array_value",
                ));
            }
            (6, WireField::Len(bytes)) => {
                out = Some(WireAny::KvListRaw(bytes));
            }
            (6, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.kvlist_value",
                ));
            }
            (7, WireField::Len(bytes)) => {
                out = Some(WireAny::Bytes(bytes));
            }
            (7, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue.bytes_value",
                ));
            }
            _ => {}
        }
        Ok(())
    })?;
    Ok(out)
}

pub(super) fn decode_key_value_wire(
    kv: &[u8],
) -> Result<Option<(&[u8], WireAny<'_>)>, ProjectionError> {
    let mut key = &[][..];
    let mut value = None;
    super::for_each_field(kv, |field, field_value| {
        match (field, field_value) {
            (1, WireField::Len(bytes)) => {
                key = super::require_utf8(bytes, "invalid UTF-8 attribute key")?;
            }
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for KeyValue.key",
                ));
            }
            (2, WireField::Len(bytes)) => {
                if let Some(decoded) = decode_any_value_wire(bytes)? {
                    value = Some(decoded);
                }
            }
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for KeyValue.value",
                ));
            }
            _ => {}
        }
        Ok(())
    })?;
    Ok(value.map(|value| (key, value)))
}

pub(super) fn wire_any_field_kind(value: &WireAny<'_>) -> FieldKind {
    match value {
        WireAny::String(_) => FieldKind::Utf8View,
        WireAny::Bool(_) => FieldKind::Bool,
        WireAny::Int(_) => FieldKind::Int64,
        WireAny::Double(_) => FieldKind::Float64,
        WireAny::ArrayRaw(_) => FieldKind::Utf8View,
        WireAny::KvListRaw(_) => FieldKind::Utf8View,
        WireAny::Bytes(_) => FieldKind::Utf8View,
    }
}

pub(super) fn write_wire_any(
    builder: &mut ColumnarBatchBuilder,
    handle: FieldHandle,
    value: WireAny<'_>,
    scratch: &mut WireScratch,
    string_storage: StringStorage,
) -> Result<(), ProjectionError> {
    match value {
        WireAny::String(value) => super::write_wire_str(builder, handle, value, string_storage)?,
        WireAny::Bool(value) => builder.write_bool(handle, value),
        WireAny::Int(value) => builder.write_i64(handle, value),
        WireAny::Double(value) => builder.write_f64(handle, value),
        WireAny::Bytes(value) => super::write_hex_field(builder, handle, value)?,
        WireAny::ArrayRaw(value) => {
            super::write_wire_any_complex_json(builder, handle, WireAny::ArrayRaw(value), scratch)?;
        }
        WireAny::KvListRaw(value) => {
            super::write_wire_any_complex_json(
                builder,
                handle,
                WireAny::KvListRaw(value),
                scratch,
            )?;
        }
    }
    Ok(())
}

pub(super) fn write_wire_any_as_string(
    builder: &mut ColumnarBatchBuilder,
    handle: FieldHandle,
    value: WireAny<'_>,
    scratch: &mut WireScratch,
    string_storage: StringStorage,
) -> Result<(), ProjectionError> {
    match value {
        WireAny::String(value) => super::write_wire_str(builder, handle, value, string_storage)?,
        WireAny::Bool(true) => {
            builder
                .write_str_bytes(handle, b"true")
                .map_err(|e| ProjectionError::Batch(e.to_string()))?;
        }
        WireAny::Bool(false) => {
            builder
                .write_str_bytes(handle, b"false")
                .map_err(|e| ProjectionError::Batch(e.to_string()))?;
        }
        WireAny::Int(value) => {
            scratch.decimal.clear();
            let mut buf = itoa::Buffer::new();
            scratch
                .decimal
                .extend_from_slice(buf.format(value).as_bytes());
            builder
                .write_str_bytes(handle, &scratch.decimal)
                .map_err(|e| ProjectionError::Batch(e.to_string()))?;
        }
        WireAny::Double(value) => {
            scratch.decimal.clear();
            let mut buf = ryu::Buffer::new();
            scratch
                .decimal
                .extend_from_slice(buf.format(value).as_bytes());
            builder
                .write_str_bytes(handle, &scratch.decimal)
                .map_err(|e| ProjectionError::Batch(e.to_string()))?;
        }
        WireAny::Bytes(value) => super::write_hex_field(builder, handle, value)?,
        WireAny::ArrayRaw(value) => {
            super::write_wire_any_complex_json(builder, handle, WireAny::ArrayRaw(value), scratch)?;
        }
        WireAny::KvListRaw(value) => {
            super::write_wire_any_complex_json(
                builder,
                handle,
                WireAny::KvListRaw(value),
                scratch,
            )?;
        }
    }
    Ok(())
}

/// Maximum nesting depth for recursive AnyValue JSON serialization.
/// Protects against stack overflow from deeply nested ArrayValue/KvListValue payloads.
pub(super) const MAX_ANY_VALUE_DEPTH: usize = 64;

pub(super) fn write_wire_any_json(
    value: WireAny<'_>,
    out: &mut Vec<u8>,
    scratch: &mut WireScratch,
) -> Result<(), ProjectionError> {
    write_wire_any_json_depth(value, out, scratch, 0)
}

pub(super) fn write_wire_any_json_depth(
    value: WireAny<'_>,
    out: &mut Vec<u8>,
    scratch: &mut WireScratch,
    depth: usize,
) -> Result<(), ProjectionError> {
    if depth > MAX_ANY_VALUE_DEPTH {
        return Err(ProjectionError::Invalid(
            "AnyValue nesting depth exceeds limit",
        ));
    }
    match value {
        WireAny::String(value) => {
            out.push(b'"');
            super::write_json_escaped_bytes(out, value);
            out.push(b'"');
        }
        WireAny::Bool(value) => out.extend_from_slice(if value { b"true" } else { b"false" }),
        WireAny::Int(value) => {
            scratch.decimal.clear();
            let mut buf = itoa::Buffer::new();
            scratch
                .decimal
                .extend_from_slice(buf.format(value).as_bytes());
            out.extend_from_slice(&scratch.decimal);
        }
        WireAny::Double(value) => {
            if value.is_finite() {
                scratch.decimal.clear();
                let mut buf = ryu::Buffer::new();
                scratch
                    .decimal
                    .extend_from_slice(buf.format(value).as_bytes());
                out.extend_from_slice(&scratch.decimal);
            } else if value.is_nan() {
                out.extend_from_slice(b"\"NaN\"");
            } else if value.is_sign_positive() {
                out.extend_from_slice(b"\"inf\"");
            } else {
                out.extend_from_slice(b"\"-inf\"");
            }
        }
        WireAny::Bytes(value) => {
            out.push(b'"');
            super::write_hex_to_buf(out, value);
            out.push(b'"');
        }
        WireAny::ArrayRaw(value) => write_array_value_json(value, out, scratch, depth)?,
        WireAny::KvListRaw(value) => write_kvlist_value_json(value, out, scratch, depth)?,
    }
    Ok(())
}

pub(super) fn write_array_value_json(
    array_value: &[u8],
    out: &mut Vec<u8>,
    scratch: &mut WireScratch,
    depth: usize,
) -> Result<(), ProjectionError> {
    out.push(b'[');
    let mut first = true;
    super::for_each_field(array_value, |field, field_value| {
        if field != 1 {
            return Ok(());
        }
        let WireField::Len(any_value) = field_value else {
            return Err(ProjectionError::Invalid(
                "invalid wire type for ArrayValue.values",
            ));
        };
        if !first {
            out.push(b',');
        }
        first = false;
        if let Some(value) = decode_any_value_wire(any_value)? {
            write_wire_any_json_depth(value, out, scratch, depth + 1)?;
        } else {
            out.extend_from_slice(b"null");
        }
        Ok(())
    })?;
    out.push(b']');
    Ok(())
}

pub(super) fn write_kvlist_value_json(
    kvlist_value: &[u8],
    out: &mut Vec<u8>,
    scratch: &mut WireScratch,
    depth: usize,
) -> Result<(), ProjectionError> {
    out.push(b'[');
    let mut first = true;
    super::for_each_field(kvlist_value, |field, field_value| {
        if field != 1 {
            return Ok(());
        }
        let WireField::Len(kv) = field_value else {
            return Err(ProjectionError::Invalid(
                "invalid wire type for KeyValueList.values",
            ));
        };
        if !first {
            out.push(b',');
        }
        first = false;
        write_key_value_json(kv, out, scratch, depth)?;
        Ok(())
    })?;
    out.push(b']');
    Ok(())
}

pub(super) fn write_key_value_json(
    kv: &[u8],
    out: &mut Vec<u8>,
    scratch: &mut WireScratch,
    depth: usize,
) -> Result<(), ProjectionError> {
    let mut key = &[][..];
    let mut value = None;
    super::for_each_field(kv, |field, field_value| {
        match (field, field_value) {
            (1, WireField::Len(bytes)) => {
                key = super::require_utf8(bytes, "invalid UTF-8 attribute key")?;
            }
            (1, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for KeyValue.key",
                ));
            }
            (2, WireField::Len(bytes)) => {
                value = decode_any_value_wire(bytes)?;
            }
            (2, _) => {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for KeyValue.value",
                ));
            }
            _ => {}
        }
        Ok(())
    })?;

    out.extend_from_slice(b"{\"k\":\"");
    super::write_json_escaped_bytes(out, key);
    out.extend_from_slice(b"\",\"v\":");
    if let Some(value) = value {
        write_wire_any_json_depth(value, out, scratch, depth + 1)?;
    } else {
        out.extend_from_slice(b"null");
    }
    out.push(b'}');
    Ok(())
}

fn scan_message(input: &[u8], message: MessageKind) -> Result<(), ProjectionError> {
    if message == MessageKind::AnyValue {
        return scan_any_value(input);
    }

    let mut input = input;
    while !input.is_empty() {
        let key = read_varint(&mut input)?;
        let field = decode_field_number(key)?;
        let wire = decode_wire_kind((key & 0x07) as u8)?;
        match wire {
            WireKind::Varint => {
                let _ = read_varint(&mut input)?;
            }
            WireKind::Fixed64 => consume_fixed(&mut input, 8, "truncated fixed64 field")?,
            WireKind::Len => {
                let bytes = consume_len(&mut input)?;
                if let Some(rule) = lookup_field(message, field) {
                    if rule.expected_wire != WireKind::Len {
                        return Err(ProjectionError::Invalid(
                            "invalid wire type for projected OTLP field",
                        ));
                    }
                    if let Some(child) = rule.child {
                        scan_message(bytes, child)?;
                    }
                }
            }
            WireKind::StartGroup => skip_group(&mut input, field)?,
            WireKind::EndGroup => {
                return Err(ProjectionError::Invalid("unexpected protobuf end group"));
            }
            WireKind::Fixed32 => consume_fixed(&mut input, 4, "truncated fixed32 field")?,
        }

        if let Some(rule) = lookup_field(message, field)
            && wire != rule.expected_wire
        {
            return Err(ProjectionError::Invalid(
                "invalid wire type for projected OTLP field",
            ));
        }
    }
    Ok(())
}

fn scan_any_value(input: &[u8]) -> Result<(), ProjectionError> {
    let mut input = input;
    let mut final_oneof: Option<ProjectionAction> = None;
    while !input.is_empty() {
        let key = read_varint(&mut input)?;
        let field = decode_field_number(key)?;
        let wire = decode_wire_kind((key & 0x07) as u8)?;
        match wire {
            WireKind::Varint => {
                let _ = read_varint(&mut input)?;
            }
            WireKind::Fixed64 => consume_fixed(&mut input, 8, "truncated fixed64 field")?,
            WireKind::Len => {
                let _ = consume_len(&mut input)?;
            }
            WireKind::StartGroup => skip_group(&mut input, field)?,
            WireKind::EndGroup => {
                return Err(ProjectionError::Invalid("unexpected protobuf end group"));
            }
            WireKind::Fixed32 => consume_fixed(&mut input, 4, "truncated fixed32 field")?,
        }

        if let Some(rule) = lookup_field(MessageKind::AnyValue, field) {
            if wire != rule.expected_wire {
                return Err(ProjectionError::Invalid(
                    "invalid wire type for AnyValue field",
                ));
            }
            final_oneof = Some(rule.action);
        }
    }

    if final_oneof == Some(ProjectionAction::Unsupported) {
        return Err(ProjectionError::Unsupported(
            "generated AnyValue unsupported oneof",
        ));
    }
    Ok(())
}

fn lookup_field(message: MessageKind, number: u32) -> Option<&'static FieldRule> {
    match message {
        MessageKind::ExportLogsServiceRequest => match number {
            1 => Some(&EXPORTLOGSSERVICEREQUEST_FIELDS[0]),
            _ => None,
        },
        MessageKind::ResourceLogs => match number {
            1 => Some(&RESOURCELOGS_FIELDS[0]),
            2 => Some(&RESOURCELOGS_FIELDS[1]),
            3 => Some(&RESOURCELOGS_FIELDS[2]),
            _ => None,
        },
        MessageKind::Resource => match number {
            1 => Some(&RESOURCE_FIELDS[0]),
            2 => Some(&RESOURCE_FIELDS[1]),
            3 => Some(&RESOURCE_FIELDS[2]),
            _ => None,
        },
        MessageKind::ScopeLogs => match number {
            1 => Some(&SCOPELOGS_FIELDS[0]),
            2 => Some(&SCOPELOGS_FIELDS[1]),
            3 => Some(&SCOPELOGS_FIELDS[2]),
            _ => None,
        },
        MessageKind::InstrumentationScope => match number {
            1 => Some(&INSTRUMENTATIONSCOPE_FIELDS[0]),
            2 => Some(&INSTRUMENTATIONSCOPE_FIELDS[1]),
            3 => Some(&INSTRUMENTATIONSCOPE_FIELDS[2]),
            4 => Some(&INSTRUMENTATIONSCOPE_FIELDS[3]),
            _ => None,
        },
        MessageKind::LogRecord => match number {
            1 => Some(&LOGRECORD_FIELDS[0]),
            2 => Some(&LOGRECORD_FIELDS[1]),
            3 => Some(&LOGRECORD_FIELDS[2]),
            5 => Some(&LOGRECORD_FIELDS[3]),
            6 => Some(&LOGRECORD_FIELDS[4]),
            7 => Some(&LOGRECORD_FIELDS[5]),
            8 => Some(&LOGRECORD_FIELDS[6]),
            9 => Some(&LOGRECORD_FIELDS[7]),
            10 => Some(&LOGRECORD_FIELDS[8]),
            11 => Some(&LOGRECORD_FIELDS[9]),
            12 => Some(&LOGRECORD_FIELDS[10]),
            _ => None,
        },
        MessageKind::KeyValue => match number {
            1 => Some(&KEYVALUE_FIELDS[0]),
            2 => Some(&KEYVALUE_FIELDS[1]),
            _ => None,
        },
        MessageKind::AnyValue => match number {
            1 => Some(&ANYVALUE_FIELDS[0]),
            2 => Some(&ANYVALUE_FIELDS[1]),
            3 => Some(&ANYVALUE_FIELDS[2]),
            4 => Some(&ANYVALUE_FIELDS[3]),
            5 => Some(&ANYVALUE_FIELDS[4]),
            6 => Some(&ANYVALUE_FIELDS[5]),
            7 => Some(&ANYVALUE_FIELDS[6]),
            _ => None,
        },
        MessageKind::ArrayValue => match number {
            1 => Some(&ARRAYVALUE_FIELDS[0]),
            _ => None,
        },
        MessageKind::KeyValueList => match number {
            1 => Some(&KEYVALUELIST_FIELDS[0]),
            _ => None,
        },
    }
}

fn consume_fixed(input: &mut &[u8], len: usize, msg: &'static str) -> Result<(), ProjectionError> {
    if input.len() < len {
        return Err(ProjectionError::Invalid(msg));
    }
    *input = &input[len..];
    Ok(())
}

fn consume_len<'a>(input: &mut &'a [u8]) -> Result<&'a [u8], ProjectionError> {
    let len = usize::try_from(read_varint(input)?)
        .map_err(|_err| ProjectionError::Invalid("protobuf length exceeds usize"))?;
    if input.len() < len {
        return Err(ProjectionError::Invalid("truncated length-delimited field"));
    }
    let (bytes, rest) = input.split_at(len);
    *input = rest;
    Ok(bytes)
}

fn decode_wire_kind(wire_type: u8) -> Result<WireKind, ProjectionError> {
    match wire_type {
        0 => Ok(WireKind::Varint),
        1 => Ok(WireKind::Fixed64),
        2 => Ok(WireKind::Len),
        3 => Ok(WireKind::StartGroup),
        4 => Ok(WireKind::EndGroup),
        5 => Ok(WireKind::Fixed32),
        _ => Err(ProjectionError::Invalid("invalid protobuf wire type")),
    }
}

const PROTOBUF_MAX_GROUP_DEPTH: usize = 64;

fn skip_group(input: &mut &[u8], start_field: u32) -> Result<(), ProjectionError> {
    let mut field_stack = [0u32; PROTOBUF_MAX_GROUP_DEPTH];
    let mut depth = 1usize;
    field_stack[0] = start_field;

    while !input.is_empty() {
        let key = read_varint(input)?;
        let field = decode_field_number(key)?;
        match decode_wire_kind((key & 0x07) as u8)? {
            WireKind::Varint => {
                let _ = read_varint(input)?;
            }
            WireKind::Fixed64 => consume_fixed(input, 8, "truncated fixed64 field")?,
            WireKind::Len => {
                let _ = consume_len(input)?;
            }
            WireKind::StartGroup => {
                if depth == PROTOBUF_MAX_GROUP_DEPTH {
                    return Err(ProjectionError::Invalid("protobuf group nesting too deep"));
                }
                field_stack[depth] = field;
                depth += 1;
            }
            WireKind::EndGroup => {
                if field != field_stack[depth - 1] {
                    return Err(ProjectionError::Invalid("mismatched protobuf end group"));
                }
                depth -= 1;
                if depth == 0 {
                    return Ok(());
                }
            }
            WireKind::Fixed32 => consume_fixed(input, 4, "truncated fixed32 field")?,
        }
    }
    Err(ProjectionError::Invalid("unterminated protobuf group"))
}

fn decode_field_number(key: u64) -> Result<u32, ProjectionError> {
    const PROTOBUF_MAX_FIELD_NUMBER: u64 = 0x1FFF_FFFF;

    let field = key >> 3;
    if field == 0 {
        return Err(ProjectionError::Invalid("protobuf field number zero"));
    }
    if field > PROTOBUF_MAX_FIELD_NUMBER {
        return Err(ProjectionError::Invalid(
            "protobuf field number out of range",
        ));
    }
    u32::try_from(field).map_err(|_err| ProjectionError::Invalid("protobuf field number overflow"))
}

fn read_varint(input: &mut &[u8]) -> Result<u64, ProjectionError> {
    let mut result = 0u64;
    for index in 0..10 {
        let Some((&byte, rest)) = input.split_first() else {
            return Err(ProjectionError::Invalid("truncated varint"));
        };
        *input = rest;
        if index == 9 && byte > 0x01 {
            return Err(ProjectionError::Invalid("varint overflow"));
        }
        result |= u64::from(byte & 0x7f) << (index * 7);
        if byte & 0x80 == 0 {
            return Ok(result);
        }
    }
    Err(ProjectionError::Invalid("varint overflow"))
}

#[cfg(test)]
mod generated_tests {
    use super::*;
    use ffwd_core::otlp;

    fn sample_field_for_wire(number: u32, wire: WireKind) -> Vec<u8> {
        let mut out = Vec::new();
        push_varint(
            &mut out,
            (u64::from(number) << 3) | u64::from(wire_id(wire)),
        );
        match wire {
            WireKind::Varint => push_varint(&mut out, 1),
            WireKind::Fixed64 => out.extend_from_slice(&1u64.to_le_bytes()),
            WireKind::Len => {
                push_varint(&mut out, 1);
                out.push(0);
            }
            WireKind::StartGroup => {
                push_varint(
                    &mut out,
                    (u64::from(number) << 3) | u64::from(wire_id(WireKind::EndGroup)),
                );
            }
            WireKind::EndGroup => {}
            WireKind::Fixed32 => out.extend_from_slice(&1u32.to_le_bytes()),
        }
        out
    }

    fn push_varint(out: &mut Vec<u8>, mut value: u64) {
        while value >= 0x80 {
            out.push(((value & 0x7f) as u8) | 0x80);
            value >>= 7;
        }
        out.push(value as u8);
    }

    fn push_len_field(out: &mut Vec<u8>, number: u32, bytes: &[u8]) {
        push_varint(
            out,
            (u64::from(number) << 3) | u64::from(wire_id(WireKind::Len)),
        );
        push_varint(out, bytes.len() as u64);
        out.extend_from_slice(bytes);
    }

    fn push_fixed64_field(out: &mut Vec<u8>, number: u32, value: u64) {
        push_varint(
            out,
            (u64::from(number) << 3) | u64::from(wire_id(WireKind::Fixed64)),
        );
        out.extend_from_slice(&value.to_le_bytes());
    }

    fn push_fixed32_field(out: &mut Vec<u8>, number: u32, value: u32) {
        push_varint(
            out,
            (u64::from(number) << 3) | u64::from(wire_id(WireKind::Fixed32)),
        );
        out.extend_from_slice(&value.to_le_bytes());
    }

    fn push_varint_field(out: &mut Vec<u8>, number: u32, value: u64) {
        push_varint(
            out,
            (u64::from(number) << 3) | u64::from(wire_id(WireKind::Varint)),
        );
        push_varint(out, value);
    }

    fn wire_id(wire: WireKind) -> u8 {
        match wire {
            WireKind::Varint => 0,
            WireKind::Fixed64 => 1,
            WireKind::Len => 2,
            WireKind::StartGroup => 3,
            WireKind::EndGroup => 4,
            WireKind::Fixed32 => 5,
        }
    }

    fn all_messages() -> &'static [MessageKind] {
        &[
            MessageKind::ExportLogsServiceRequest,
            MessageKind::ResourceLogs,
            MessageKind::Resource,
            MessageKind::ScopeLogs,
            MessageKind::InstrumentationScope,
            MessageKind::LogRecord,
            MessageKind::KeyValue,
            MessageKind::AnyValue,
            MessageKind::ArrayValue,
            MessageKind::KeyValueList,
        ]
    }

    fn wrong_wires(expected: WireKind) -> [WireKind; 5] {
        match expected {
            WireKind::Varint => [
                WireKind::Fixed64,
                WireKind::Len,
                WireKind::StartGroup,
                WireKind::EndGroup,
                WireKind::Fixed32,
            ],
            WireKind::Fixed64 => [
                WireKind::Varint,
                WireKind::Len,
                WireKind::StartGroup,
                WireKind::EndGroup,
                WireKind::Fixed32,
            ],
            WireKind::Len => [
                WireKind::Varint,
                WireKind::Fixed64,
                WireKind::StartGroup,
                WireKind::EndGroup,
                WireKind::Fixed32,
            ],
            WireKind::StartGroup => [
                WireKind::Varint,
                WireKind::Fixed64,
                WireKind::Len,
                WireKind::EndGroup,
                WireKind::Fixed32,
            ],
            WireKind::EndGroup => [
                WireKind::Varint,
                WireKind::Fixed64,
                WireKind::Len,
                WireKind::StartGroup,
                WireKind::Fixed32,
            ],
            WireKind::Fixed32 => [
                WireKind::Varint,
                WireKind::Fixed64,
                WireKind::Len,
                WireKind::StartGroup,
                WireKind::EndGroup,
            ],
        }
    }

    fn complex_anyvalue_field_numbers() -> &'static [u32] {
        &[5, 6]
    }

    #[test]
    fn generated_anyvalue_table_covers_all_current_oneof_fields() {
        let fields = fields_for(MessageKind::AnyValue);
        assert_eq!(fields.len(), 7);
        assert!(
            fields
                .iter()
                .any(|f| f.name == "array_value" && f.action == ProjectionAction::Project)
        );
        assert!(
            fields
                .iter()
                .any(|f| f.name == "kvlist_value" && f.action == ProjectionAction::Project)
        );
        assert!(
            fields
                .iter()
                .any(|f| f.name == "bytes_value" && f.action == ProjectionAction::Project)
        );
    }

    #[test]
    fn generated_wire_any_field_kind_matches_variant_policy() {
        assert_eq!(
            wire_any_field_kind(&WireAny::String(b"s")),
            FieldKind::Utf8View
        );
        assert_eq!(wire_any_field_kind(&WireAny::Bool(true)), FieldKind::Bool);
        assert_eq!(wire_any_field_kind(&WireAny::Int(42)), FieldKind::Int64);
        assert_eq!(
            wire_any_field_kind(&WireAny::Double(42.5)),
            FieldKind::Float64
        );
        assert_eq!(
            wire_any_field_kind(&WireAny::Bytes(b"b")),
            FieldKind::Utf8View
        );
        assert_eq!(
            wire_any_field_kind(&WireAny::ArrayRaw(&[])),
            FieldKind::Utf8View
        );
        assert_eq!(
            wire_any_field_kind(&WireAny::KvListRaw(&[])),
            FieldKind::Utf8View
        );
    }

    #[test]
    fn generated_wire_any_json_handles_scalar_and_complex_variants() {
        let mut scratch = WireScratch::default();
        let cases: &[(WireAny<'_>, &[u8])] = &[
            (WireAny::String(br#"a"b"#), br#""a\"b""#),
            (WireAny::Bool(true), b"true"),
            (WireAny::Int(-42), b"-42"),
            (WireAny::Double(12.5), b"12.5"),
            (WireAny::Bytes(&[0xde, 0xad]), br#""dead""#),
            (WireAny::ArrayRaw(&[]), b"[]"),
            (WireAny::KvListRaw(&[]), b"[]"),
        ];

        for &(value, expected) in cases {
            let mut out = Vec::new();
            write_wire_any_json(value, &mut out, &mut scratch)
                .expect("generated JSON writer should handle projected variant");
            assert_eq!(out, expected);
        }
    }

    #[test]
    fn generated_complex_json_writers_handle_nested_messages() {
        let mut scratch = WireScratch::default();
        let any_string = [10, 1, b'x'];
        let array = [10, 3, 10, 1, b'x'];
        let kv = [10, 1, b'k', 18, 3, 10, 1, b'v'];
        let kvlist = [10, 8, 10, 1, b'k', 18, 3, 10, 1, b'v'];

        let mut out = Vec::new();
        write_array_value_json(&array, &mut out, &mut scratch, 0)
            .expect("generated array JSON writer should decode repeated AnyValue");
        assert_eq!(out, br#"["x"]"#);

        out.clear();
        write_key_value_json(&kv, &mut out, &mut scratch, 0)
            .expect("generated key value JSON writer should decode KeyValue");
        assert_eq!(out, br#"{"k":"k","v":"v"}"#);

        out.clear();
        write_kvlist_value_json(&kvlist, &mut out, &mut scratch, 0)
            .expect("generated kvlist JSON writer should decode repeated KeyValue");
        assert_eq!(out, br#"[{"k":"k","v":"v"}]"#);

        out.clear();
        write_wire_any_json(WireAny::ArrayRaw(&array), &mut out, &mut scratch)
            .expect("generated AnyValue JSON writer should dispatch arrays");
        assert_eq!(out, br#"["x"]"#);

        out.clear();
        write_wire_any_json(WireAny::String(&any_string[2..]), &mut out, &mut scratch)
            .expect("generated AnyValue JSON writer should keep scalar dispatch");
        assert_eq!(out, br#""x""#);
    }

    #[test]
    fn generated_planned_appenders_write_expected_columns() {
        use arrow::array::{Int64Array, StringViewArray};

        let (plan, handles) = build_otlp_plan();
        let mut builder = ColumnarBatchBuilder::new(plan);
        let mut scratch = WireScratch::default();

        builder.begin_batch();
        builder.begin_row();
        handles.write_timestamp(&mut builder, 11);
        handles.write_observed_timestamp(&mut builder, 12);
        handles
            .write_severity(&mut builder, b"INFO", StringStorage::Decoded)
            .expect("severity appender should write");
        handles.write_severity_number(&mut builder, 9);
        handles
            .write_body(
                &mut builder,
                WireAny::String(b"body"),
                &mut scratch,
                StringStorage::Decoded,
            )
            .expect("body appender should write");
        handles
            .write_trace_id(&mut builder, &[0xab, 0xcd])
            .expect("trace id appender should write");
        handles
            .write_span_id(&mut builder, &[0x12, 0x34])
            .expect("span id appender should write");
        handles.write_flags(&mut builder, 1);
        handles
            .write_scope_name(&mut builder, b"scope", StringStorage::Decoded)
            .expect("scope name appender should write");
        handles
            .write_scope_version(&mut builder, b"1.2.3", StringStorage::Decoded)
            .expect("scope version appender should write");
        builder.end_row();

        let batch = builder
            .finish_batch()
            .expect("generated appenders should produce a batch");

        let int_value = |name: &str| -> i64 {
            let column = batch.column(batch.schema().index_of(name).expect("planned int field"));
            column
                .as_any()
                .downcast_ref::<Int64Array>()
                .expect("planned field should be Int64")
                .value(0)
        };
        let str_value = |name: &str| -> String {
            let column = batch.column(batch.schema().index_of(name).expect("planned string field"));
            column
                .as_any()
                .downcast_ref::<StringViewArray>()
                .expect("planned field should be StringViewArray")
                .value(0)
                .to_owned()
        };

        assert_eq!(int_value(field_names::TIMESTAMP), 11);
        assert_eq!(int_value(field_names::OBSERVED_TIMESTAMP), 12);
        assert_eq!(str_value(field_names::SEVERITY), "INFO");
        assert_eq!(int_value(field_names::SEVERITY_NUMBER), 9);
        assert_eq!(str_value(field_names::BODY), "body");
        assert_eq!(str_value(field_names::TRACE_ID), "abcd");
        assert_eq!(str_value(field_names::SPAN_ID), "1234");
        assert_eq!(int_value(field_names::FLAGS), 1);
        assert_eq!(str_value(field_names::SCOPE_NAME), "scope");
        assert_eq!(str_value(field_names::SCOPE_VERSION), "1.2.3");
    }

    #[test]
    fn generated_scope_decoder_merges_partial_scope_messages() {
        let mut scope_fields = ScopeFields::default();
        let mut name = Vec::new();
        let mut version = Vec::new();
        push_len_field(
            &mut name,
            field_numbers::INSTRUMENTATION_SCOPE_NAME,
            b"scope-a",
        );
        push_len_field(
            &mut version,
            field_numbers::INSTRUMENTATION_SCOPE_VERSION,
            b"1.2.3",
        );

        merge_scope_wire(&name, &mut scope_fields).expect("scope name should decode");
        merge_scope_wire(&version, &mut scope_fields).expect("scope version should decode");

        assert_eq!(scope_fields.name, Some(b"scope-a".as_slice()));
        assert_eq!(scope_fields.version, Some(b"1.2.3".as_slice()));
    }

    #[test]
    fn generated_log_record_decoder_extracts_projected_fields() {
        let mut body = Vec::new();
        push_len_field(&mut body, field_numbers::ANY_VALUE_STRING_VALUE, b"body");

        let mut attr_value = Vec::new();
        push_len_field(
            &mut attr_value,
            field_numbers::ANY_VALUE_STRING_VALUE,
            b"value",
        );

        let mut attr = Vec::new();
        push_len_field(&mut attr, field_numbers::KEY_VALUE_KEY, b"key");
        push_len_field(&mut attr, field_numbers::KEY_VALUE_VALUE, &attr_value);

        let trace_id = [0x11; 16];
        let span_id = [0x22; 8];
        let mut log_record = Vec::new();
        push_fixed64_field(
            &mut log_record,
            field_numbers::LOG_RECORD_TIME_UNIX_NANO,
            11,
        );
        push_fixed64_field(
            &mut log_record,
            field_numbers::LOG_RECORD_OBSERVED_TIME_UNIX_NANO,
            12,
        );
        push_varint_field(
            &mut log_record,
            field_numbers::LOG_RECORD_SEVERITY_NUMBER,
            9,
        );
        push_len_field(
            &mut log_record,
            field_numbers::LOG_RECORD_SEVERITY_TEXT,
            b"INFO",
        );
        push_len_field(&mut log_record, field_numbers::LOG_RECORD_BODY, &body);
        push_len_field(
            &mut log_record,
            field_numbers::LOG_RECORD_TRACE_ID,
            &trace_id,
        );
        push_len_field(&mut log_record, field_numbers::LOG_RECORD_SPAN_ID, &span_id);
        push_fixed32_field(&mut log_record, field_numbers::LOG_RECORD_FLAGS, 1);
        push_len_field(&mut log_record, field_numbers::LOG_RECORD_ATTRIBUTES, &attr);

        let mut attr_ranges = Vec::new();
        let decoded = decode_log_record_fields(&log_record, &mut attr_ranges)
            .expect("log record fields should decode");

        assert_eq!(decoded.time_unix_nano, 11);
        assert_eq!(decoded.observed_time_unix_nano, 12);
        assert_eq!(decoded.severity_number, 9);
        assert_eq!(decoded.severity_text, Some(b"INFO".as_slice()));
        assert_eq!(decoded.trace_id, Some(trace_id.as_slice()));
        assert_eq!(decoded.span_id, Some(span_id.as_slice()));
        assert_eq!(decoded.flags, 1);
        match decoded.body {
            Some(WireAny::String(value)) => assert_eq!(value, b"body"),
            _ => panic!("body should decode as string AnyValue"),
        }
        assert_eq!(attr_ranges.len(), 1);
        let (start, len) = attr_ranges[0];
        assert_eq!(&log_record[start..start + len], attr.as_slice());
    }

    #[test]
    fn generated_len_visitors_yield_expected_payloads() {
        let mut export = Vec::new();
        let mut resource_logs = Vec::new();
        let mut resource = Vec::new();
        let mut scope_logs = Vec::new();

        push_len_field(&mut resource, field_numbers::RESOURCE_ATTRIBUTES, b"attr");
        push_len_field(&mut scope_logs, field_numbers::SCOPE_LOGS_SCOPE, b"scope");
        push_len_field(
            &mut scope_logs,
            field_numbers::SCOPE_LOGS_LOG_RECORDS,
            b"log",
        );
        push_len_field(
            &mut resource_logs,
            field_numbers::RESOURCE_LOGS_RESOURCE,
            &resource,
        );
        push_len_field(
            &mut resource_logs,
            field_numbers::RESOURCE_LOGS_SCOPE_LOGS,
            &scope_logs,
        );
        push_len_field(
            &mut export,
            field_numbers::EXPORT_LOGS_REQUEST_RESOURCE_LOGS,
            &resource_logs,
        );

        let mut seen_resource_logs = Vec::new();
        for_each_export_resource_logs(&export, |payload| {
            seen_resource_logs.push(payload.to_vec());
            Ok(())
        })
        .expect("export visitor should yield resource logs");
        assert_eq!(seen_resource_logs, vec![resource_logs.clone()]);

        let mut seen_resources = Vec::new();
        for_each_resource_logs_resource(&resource_logs, |payload| {
            seen_resources.push(payload.to_vec());
            Ok(())
        })
        .expect("resource visitor should yield resource payload");
        assert_eq!(seen_resources, vec![resource.clone()]);

        let mut seen_scope_logs = Vec::new();
        for_each_resource_logs_scope_logs(&resource_logs, |payload| {
            seen_scope_logs.push(payload.to_vec());
            Ok(())
        })
        .expect("scope logs visitor should yield scope logs payload");
        assert_eq!(seen_scope_logs, vec![scope_logs.clone()]);

        let mut seen_attrs = Vec::new();
        for_each_resource_attribute(&resource, |payload| {
            seen_attrs.push(payload.to_vec());
            Ok(())
        })
        .expect("resource attribute visitor should yield attribute payload");
        assert_eq!(seen_attrs, vec![b"attr".to_vec()]);

        let mut seen_scopes = Vec::new();
        for_each_scope_logs_scope(&scope_logs, |payload| {
            seen_scopes.push(payload.to_vec());
            Ok(())
        })
        .expect("scope visitor should yield scope payload");
        assert_eq!(seen_scopes, vec![b"scope".to_vec()]);

        let mut seen_logs = Vec::new();
        for_each_scope_logs_log_record(&scope_logs, |payload| {
            seen_logs.push(payload.to_vec());
            Ok(())
        })
        .expect("log visitor should yield log payload");
        assert_eq!(seen_logs, vec![b"log".to_vec()]);
    }

    #[test]
    fn generated_len_visitors_reject_wrong_wire() {
        let payload =
            sample_field_for_wire(field_numbers::RESOURCE_LOGS_SCOPE_LOGS, WireKind::Varint);
        let err = for_each_resource_logs_scope_logs(&payload, |_| Ok(()))
            .expect_err("wrong wire should be invalid");
        assert!(matches!(err, ProjectionError::Invalid(_)));
    }

    #[test]
    fn generated_logrecord_table_tracks_projected_protocol_fields() {
        let fields = fields_for(MessageKind::LogRecord);
        assert!(
            fields
                .iter()
                .any(|f| f.name == "body" && f.child == Some(MessageKind::AnyValue))
        );
        assert!(
            fields
                .iter()
                .any(|f| f.name == "attributes" && f.child == Some(MessageKind::KeyValue))
        );
        assert!(
            fields
                .iter()
                .any(|f| f.name == "flags" && f.expected_wire == WireKind::Fixed32)
        );
    }

    #[test]
    fn generated_projection_field_numbers_match_core_otlp_constants() {
        assert_eq!(
            EXPORTLOGSSERVICEREQUEST_FIELDS
                .iter()
                .find(|f| f.name == "resource_logs")
                .expect("projection field")
                .number,
            otlp::EXPORT_LOGS_REQUEST_RESOURCE_LOGS
        );
        assert_eq!(
            RESOURCELOGS_FIELDS
                .iter()
                .find(|f| f.name == "resource")
                .expect("projection field")
                .number,
            otlp::RESOURCE_LOGS_RESOURCE
        );
        assert_eq!(
            RESOURCELOGS_FIELDS
                .iter()
                .find(|f| f.name == "scope_logs")
                .expect("projection field")
                .number,
            otlp::RESOURCE_LOGS_SCOPE_LOGS
        );
        assert_eq!(
            RESOURCE_FIELDS
                .iter()
                .find(|f| f.name == "attributes")
                .expect("projection field")
                .number,
            otlp::RESOURCE_ATTRIBUTES
        );
        assert_eq!(
            SCOPELOGS_FIELDS
                .iter()
                .find(|f| f.name == "scope")
                .expect("projection field")
                .number,
            otlp::SCOPE_LOGS_SCOPE
        );
        assert_eq!(
            SCOPELOGS_FIELDS
                .iter()
                .find(|f| f.name == "log_records")
                .expect("projection field")
                .number,
            otlp::SCOPE_LOGS_LOG_RECORDS
        );
        assert_eq!(
            INSTRUMENTATIONSCOPE_FIELDS
                .iter()
                .find(|f| f.name == "name")
                .expect("projection field")
                .number,
            otlp::INSTRUMENTATION_SCOPE_NAME
        );
        assert_eq!(
            INSTRUMENTATIONSCOPE_FIELDS
                .iter()
                .find(|f| f.name == "version")
                .expect("projection field")
                .number,
            otlp::INSTRUMENTATION_SCOPE_VERSION
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "time_unix_nano")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_TIME_UNIX_NANO
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "severity_number")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_SEVERITY_NUMBER
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "severity_text")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_SEVERITY_TEXT
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "body")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_BODY
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "attributes")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_ATTRIBUTES
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "flags")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_FLAGS
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "trace_id")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_TRACE_ID
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "span_id")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_SPAN_ID
        );
        assert_eq!(
            LOGRECORD_FIELDS
                .iter()
                .find(|f| f.name == "observed_time_unix_nano")
                .expect("projection field")
                .number,
            otlp::LOG_RECORD_OBSERVED_TIME_UNIX_NANO
        );
        assert_eq!(
            KEYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "key")
                .expect("projection field")
                .number,
            otlp::KEY_VALUE_KEY
        );
        assert_eq!(
            KEYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "value")
                .expect("projection field")
                .number,
            otlp::KEY_VALUE_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "string_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_STRING_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "bool_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_BOOL_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "int_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_INT_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "double_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_DOUBLE_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "array_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_ARRAY_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "kvlist_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_KVLIST_VALUE
        );
        assert_eq!(
            ANYVALUE_FIELDS
                .iter()
                .find(|f| f.name == "bytes_value")
                .expect("projection field")
                .number,
            otlp::ANY_VALUE_BYTES_VALUE
        );
    }

    #[test]
    fn generated_decode_anyvalue_keeps_last_oneof_value() {
        let bytes = [42, 0, 10, 2, b'o', b'k'];
        let value = decode_any_value_wire(&bytes).expect("generated AnyValue should decode");
        match value {
            Some(WireAny::String(value)) => assert_eq!(value, b"ok"),
            _ => panic!("unexpected generated AnyValue variant"),
        }
    }

    #[test]
    fn generated_decode_anyvalue_terminal_complex_keeps_last_oneof_value() {
        let bytes = [10, 2, b'o', b'k', 42, 0];
        let value = decode_any_value_wire(&bytes).expect("terminal oneof should decode");
        assert!(matches!(value, Some(WireAny::ArrayRaw(_))));
    }

    #[test]
    fn generated_decode_anyvalue_wrong_wire_is_invalid() {
        let bytes = [8, 1];
        let err = match decode_any_value_wire(&bytes) {
            Ok(_) => panic!("wrong wire type should be invalid"),
            Err(err) => err,
        };
        assert!(matches!(err, ProjectionError::Invalid(_)));
    }

    #[test]
    fn generated_decode_keyvalue_keeps_last_key_and_value() {
        let bytes = [
            10, 3, b'o', b'l', b'd', 10, 3, b'k', b'e', b'y', 18, 4, 10, 2, b'o', b'k',
        ];
        let value = decode_key_value_wire(&bytes).expect("generated KeyValue should decode");
        match value {
            Some((key, WireAny::String(value))) => {
                assert_eq!(key, b"key");
                assert_eq!(value, b"ok");
            }
            _ => panic!("unexpected generated KeyValue variant"),
        }
    }

    #[test]
    fn generated_decode_keyvalue_without_value_is_omitted() {
        let bytes = [10, 3, b'k', b'e', b'y'];
        let value = decode_key_value_wire(&bytes).expect("generated KeyValue should decode");
        assert!(value.is_none());
    }

    #[test]
    fn generated_known_fields_reject_wrong_wire_types() {
        for &message in all_messages() {
            for rule in fields_for(message) {
                for wrong_wire in wrong_wires(rule.expected_wire) {
                    let payload = sample_field_for_wire(rule.number, wrong_wire);
                    let err = scan_message(&payload, message)
                        .expect_err("known field wrong wire should be invalid");
                    assert!(
                        matches!(err, ProjectionError::Invalid(_)),
                        "message={message:?} field={} wrong_wire={wrong_wire:?} err={err:?}",
                        rule.name
                    );
                }
            }
        }
    }

    #[test]
    fn generated_ignored_fields_accept_expected_wire() {
        for &message in all_messages() {
            for rule in fields_for(message) {
                if rule.action != ProjectionAction::Ignore {
                    continue;
                }
                let payload = sample_field_for_wire(rule.number, rule.expected_wire);
                scan_message(&payload, message)
                    .expect("ignored field with expected wire should be accepted");
            }
        }
    }

    #[test]
    fn generated_ignored_fields_reject_wrong_wire() {
        for &message in all_messages() {
            for rule in fields_for(message) {
                if rule.action != ProjectionAction::Ignore {
                    continue;
                }
                for wrong_wire in wrong_wires(rule.expected_wire) {
                    let payload = sample_field_for_wire(rule.number, wrong_wire);
                    let err = scan_message(&payload, message)
                        .expect_err("ignored field wrong wire should be invalid");
                    assert!(
                        matches!(err, ProjectionError::Invalid(_)),
                        "message={message:?} field={} wrong_wire={wrong_wire:?} err={err:?}",
                        rule.name
                    );
                }
            }
        }
    }

    #[test]
    fn generated_anyvalue_complex_shapes_are_projected() {
        for &field_number in complex_anyvalue_field_numbers() {
            let payload = sample_field_for_wire(field_number, WireKind::Len);
            scan_message(&payload, MessageKind::AnyValue)
                .expect("complex AnyValue shape should classify for projection");
            let value = decode_any_value_wire(&payload).expect("complex AnyValue should decode");
            assert!(matches!(
                value,
                Some(WireAny::ArrayRaw(_)) | Some(WireAny::KvListRaw(_))
            ));
        }
    }

    #[test]
    fn generated_anyvalue_oneof_last_value_wins_for_complex_and_primitive() {
        let projected = sample_field_for_wire(otlp::ANY_VALUE_STRING_VALUE, WireKind::Len);
        for &field_number in complex_anyvalue_field_numbers() {
            let complex = sample_field_for_wire(field_number, WireKind::Len);

            let mut complex_then_projected = complex.clone();
            complex_then_projected.extend_from_slice(&projected);
            let value = decode_any_value_wire(&complex_then_projected)
                .expect("terminal projected oneof should decode");
            assert!(matches!(value, Some(WireAny::String(_))));

            let mut projected_then_complex = projected.clone();
            projected_then_complex.extend_from_slice(&complex);
            let value = decode_any_value_wire(&projected_then_complex)
                .expect("terminal complex oneof should decode");
            assert!(matches!(
                value,
                Some(WireAny::ArrayRaw(_)) | Some(WireAny::KvListRaw(_))
            ));
        }
    }

    #[test]
    fn generated_security_malformed_wire_corpus_is_rejected() {
        let malformed_cases: &[&[u8]] = &[
            &[0x0a, 0x02, 0x01],
            &[
                0x08, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x02,
            ],
            &[0x53, 0x64],
            &[0x0b, 0x13],
            &[0x0c],
        ];
        for bytes in malformed_cases {
            let err = classify_projection_support(bytes)
                .expect_err("malformed protobuf bytes must be rejected");
            assert!(matches!(err, ProjectionError::Invalid(_)));
        }
    }
}
