use std::fmt::Write as _;

pub(crate) type InputTemplate = ffwd_config::docspec::TemplateDoc;
pub(crate) type OutputTemplate = ffwd_config::docspec::TemplateDoc;
pub(crate) type UseCaseTemplate = ffwd_config::docspec::UseCaseDoc;

/// Input presets currently surfaced by `ff wizard`.
pub(crate) const INPUT_TEMPLATES: &[InputTemplate] = ffwd_config::docspec::INPUT_TEMPLATES;

/// Output presets currently surfaced by `ff wizard`.
pub(crate) const OUTPUT_TEMPLATES: &[OutputTemplate] = ffwd_config::docspec::OUTPUT_TEMPLATES;

/// Opinionated end-to-end presets for `ff wizard`.
pub(crate) const USE_CASE_TEMPLATES: &[UseCaseTemplate] = ffwd_config::docspec::USE_CASE_TEMPLATES;

fn push_pipeline_list_item_body(out: &mut String, section_name: &str, snippet_body: &str) {
    let lines = normalized_snippet_lines(snippet_body);
    if let Some((first, rest)) = lines.split_first() {
        let _ = writeln!(out, "    {section_name}:");
        let _ = writeln!(out, "      - {first}");
        for line in rest {
            let _ = writeln!(out, "        {line}");
        }
    }
}

fn normalized_snippet_lines(snippet_body: &str) -> Vec<&str> {
    let lines: Vec<&str> = snippet_body
        .lines()
        .filter(|line| !line.trim().is_empty())
        .collect();
    let base_indent = lines
        .iter()
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or(0);
    lines
        .into_iter()
        .map(|line| line.get(base_indent..).unwrap_or_else(|| line.trim_start()))
        .collect()
}

/// Render a complete config from an input/output template pair and SQL text.
pub(crate) fn render_config(
    input: &InputTemplate,
    output: &OutputTemplate,
    transform_sql: &str,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by ff wizard\n");
    out.push_str("# Fill in paths/endpoints/credentials for your environment.\n\n");
    out.push_str("pipelines:\n  default:\n");
    push_pipeline_list_item_body(&mut out, "inputs", input.snippet.trim_end());
    if !transform_sql.trim().is_empty() {
        out.push_str("    transform: |\n");
        for line in transform_sql.lines() {
            let _ = writeln!(out, "      {line}");
        }
    }
    push_pipeline_list_item_body(&mut out, "outputs", output.snippet.trim_end());
    out.push_str("\n# Optional: diagnostics server\n");
    out.push_str("# server:\n#   diagnostics: 127.0.0.1:9191\n");
    out
}

/// Render a use-case preset, optionally with a custom SQL transform.
pub(crate) fn render_use_case(use_case: &UseCaseTemplate, sql: &str) -> String {
    let input_snippet =
        ffwd_config::docspec::input_template(use_case.input_id).map_or("", |t| t.snippet);
    let output_snippet =
        ffwd_config::docspec::output_template(use_case.output_id).map_or("", |t| t.snippet);
    let mut out = String::new();
    out.push_str("# ff example\n");
    let _ = writeln!(out, "# Use case: {}", use_case.title);
    let _ = writeln!(out, "# {}", use_case.description);
    out.push('\n');
    out.push_str("pipelines:\n  default:\n");
    push_pipeline_list_item_body(&mut out, "inputs", input_snippet.trim_end());
    out.push_str("    transform: |\n");
    for line in sql.lines() {
        let _ = writeln!(out, "      {line}");
    }
    push_pipeline_list_item_body(&mut out, "outputs", output_snippet.trim_end());
    out.push_str("\n# Optional: diagnostics\n# server:\n#   diagnostics: 127.0.0.1:9191\n");
    out
}
